[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
dependencies = [
    "kreuzberg[api,easyocr,paddleocr]==3.11.0",
    "uvicorn",
]
description = "pyonb wrapper around kreuzberg"
name = "pyonb-kreuzberg"
readme = "README.md"
requires-python = ">=3.11"
version = "0.1.0"
