[project]
name = "pyonb-kreuzberg"
version = "0.1.0"
description = "pyonb wrapper around kreuzberg"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kreuzberg[api,easyocr,paddleocr]==3.11.0",
    "uvicorn",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
