[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
dependencies = [
    "cmake",
    "datasets==2.20.0",
    "fastapi==0.111.0",
    "paddleocr==2.10.0",
    "pdf2image==1.17.0",
    "pillow==11.1.0",
    "python-multipart",
    "python-poppler",
    "requests",
    "setuptools",
    "uvicorn[standard]",
]
description = "pyonb wrapper around paddleocr"
name = "pyonb-paddleocr"
readme = "README.md"
requires-python = ">=3.11"
version = "0.1.0"
