[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
dependencies = [
    "accelerate",
    "fastapi[standard]",
    "marker-pdf",
    "ollama",
    "python-dotenv",
    "requests",
    "uvicorn",
]
description = "pyonb wrapper around marker"
name = "pyonb-marker"
readme = "README.md"
requires-python = ">=3.11"
version = "0.1.0"
