---
name: Dev Issue
description: Create a new issue or task for pyonb
labels:
  - design
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the development task.
    validations:
      required: true
  - type: textarea
    id: definition_of_done
    attributes:
      label: Definition of Done / Acceptance Criteria
      description: What can someone see/do when this task is done.
      placeholder: "- [ ] The export data is available in the xxx format, including age of the patient at the time of imaging..."
    validations:
      required: true
  - type: textarea
    id: testing
    attributes:
      label: Testing
      description: Specific testing considerations for this task to be done
      placeholder: "- [ ] Passed integration testing that uses the correct modality..."
    validations:
      required: false
  - type: textarea
    id: documentation
    attributes:
      label: Documentation
      description: Documentation to be completed along with this task
      placeholder: "- [ ] Update module README and user guide..."
    validations:
      required: false
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Enter the github issue number that the requirement is dependent on, in the form `- [ ] #1` to make a checklist
      placeholder: "- [ ] #1"
    validations:
      required: false
  - type: textarea
    id: details
    attributes:
      label: Details and Comments
      description: Other details or comments
      placeholder: The algorithm used is based on...
    validations:
      required: false