name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      PYTHON_ENV: test

    services:
      docker:
        image: docker:24.0.5
        options: --privileged

    strategy:
      matrix:
        python-version:
          - "3.11"
          # - "3.12"
          # - "3.13"

    steps:
      - name: Checkout source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Cache tox
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: .tox
          key: tox-${{hashFiles('pyproject.toml') }}

      - name: Cache docker/setup-buildx
        uses: docker/setup-buildx-action@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install Python dependencies
        run: |
            uv sync

      - name: Display Python dependencies
        run: |
            uv pip list

      - name: Copy .env file
        run: |
          cp ./tests/.env.tests ./tests/.env
          cat ./tests/.env

      - name: Start Docker services
        run: |
          docker compose --env-file ./tests/.env --profile marker --profile sparrow up -d

      - name: Wait for services to be healthy
        run: |
          docker compose ps
          docker compose logs
          sleep 90

      # - name: Set up python
      #   uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
      #   with:
      #     python-version: ${{ matrix.python-version }}
      #     cache: pip
      #     cache-dependency-path: pyproject.toml

      # - name: Install dependencies
      #   run: python -m pip install tox tox-gh

      - name: Test with tox
        run: tox run

      - name: Tear down services
        if: always()
        run: docker compose --profile marker --profile sparrow down --rmi all --volumes --remove-orphans
